[package]
name = "tb-report"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true }
colored.workspace = true
serde.workspace = true
serde_json.workspace = true
tb-diff.workspace = true
tb-rules.workspace = true
