[package]
name = "tb-parse"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tb-diff.workspace = true
tree-sitter.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-rust.workspace = true

[dev-dependencies]
tempfile.workspace = true
